<?php
$mobile_icons = array(
	'docomo' => array(
		'Xaquarius'		=> '&#xE650;',
		'Xarea'		=> '&#xE6F8;',
		'Xaries'		=> '&#xE646;',
		'Xatm'		=> '&#xE668;',
		'Xbank'		=> '&#xE667;',
		'Xbar'		=> '&#xE671;',
		'Xbarber'		=> '&#xE675;',
		'Xbeer'		=> '&#xE672;',
		'Xbird'		=> '&#xE74F;',
		'Xbomb'		=> '&#xE6FE;',
		'Xbook'		=> '&#xE683;',
		'Xbuilding'		=> '&#xE664;',
		'Xbulb'		=> '&#xE6FB;',
		'Xcaf?'		=> '&#xE670;',
		'Xcake'		=> '&#xE686;',
		'Xcamera'		=> '&#xE681;',
		'Xcamp'		=> '&#xE67D;',
		'Xcancer'		=> '&#xE649;',
		'Xcapricorn'		=> '&#xE64F;',
		'Xcar'		=> '&#xE65E;',
		'Xcat'		=> '&#xE6A2;',
		'Xcd'		=> '&#xE68C;',
		'Xcharge'		=> '&#xE6D6;',
		'Xcheckerflag'		=> '&#xE659;',
		'Xclock'		=> '&#xE6BA;',
		'Xcloud'		=> '&#xE63F;',
		'Xclover'		=> '&#xE741;',
		'Xclub'		=> '&#xE690;',
		'Xcopyright'		=> '&#xE731;',
		'Xcrown'		=> '&#xE71A;',
		'Xcvs'		=> '&#xE66A;',
		'Xdiacritic'		=> '&#xE6F6;',
		'Xdiamond'		=> '&#xE68F;',
		'Xdocument'		=> '&#xE689;',
		'Xdog'		=> '&#xE6A1;',
		'Xear'		=> '&#xE692;',
		'Xempty'		=> '&#xE739;',
		'Xfastfood'		=> '&#xE673;',
		'Xfaxto'		=> '&#xE6D0;',
		'Xfish'		=> '&#xE751;',
		'Xflag'		=> '&#xE6DE;',
		'Xfootball'		=> '&#xE656;',
		'Xforbidden'		=> '&#xE738;',
		'Xfree'		=> '&#xE6D7;',
		'Xfull'		=> '&#xE73B;',
		'Xgame'		=> '&#xE68B;',
		'Xgas'		=> '&#xE66B;',
		'Xgemini'		=> '&#xE648;',
		'Xglasses'		=> '&#xE69A;',
		'Xgolf'		=> '&#xE654;',
		'Xgood'		=> '&#xE727;',
		'Xhandicapped'		=> '&#xE69B;',
		'Xheadset'		=> '&#xE67A;',
		'Xheart'		=> '&#xE68D;',
		'Xhorse'		=> '&#xE679;',
		'Xhospital'		=> '&#xE666;',
		'Xhotel'		=> '&#xE669;',
		'Xhouse'		=> '&#xE663;',
		'Xid'		=> '&#xE6D8;',
		'Xkaraoke'		=> '&#xE676;',
		'Xkey'		=> '&#xE6D9;',
		'Xleo'		=> '&#xE64A;',
		'Xlibra'		=> '&#xE64C;',
		'Xlip'		=> '&#xE6F9;',
		'Xmail'		=> '&#xE6D3;',
		'Xmailto'		=> '&#xE6CF;',
		'Xmetro'		=> '&#xE65C;',
		'Xmobile'		=> '&#xE688;',
		'Xmoney'		=> '&#xE6AD;',
		'Xnew'		=> '&#xE6DD;',
		'Xnosmoking'		=> '&#xE680;',
		'Xnum0'		=> '&#xE6EB;',
		'Xnum1'		=> '&#xE6E2;',
		'Xnum2'		=> '&#xE6E3;',
		'Xnum3'		=> '&#xE6E4;',
		'Xnum4'		=> '&#xE6E5;',
		'Xnum5'		=> '&#xE6E6;',
		'Xnum6'		=> '&#xE6E7;',
		'Xnum7'		=> '&#xE6E8;',
		'Xnum8'		=> '&#xE6E9;',
		'Xnum9'		=> '&#xE6EA;',
		'Xok'		=> '&#xE70B;',
		'Xpaper'		=> '&#xE695;',
		'Xparking'		=> '&#xE66C;',
		'Xpc'		=> '&#xE716;',
		'Xpen'		=> '&#xE6AE;',
		'Xpencil'		=> '&#xE719;',
		'Xpenguin'		=> '&#xE750;',
		'Xpeople'		=> '&#xE6B1;',
		'Xpisces'		=> '&#xE651;',
		'Xplain'		=> '&#xE662;',
		'Xpost'		=> '&#xE665;',
		'Xpresent'		=> '&#xE685;',
		'Xrainy'		=> '&#xE640;',
		'Xregarded'		=> '&#xE736;',
		'Xrestaurant'		=> '&#xE66F;',
		'Xreturn'		=> '&#xE6DA;',
		'Xribbon'		=> '&#xE684;',
		'Xring'		=> '&#xE71B;',
		'Xrock'		=> '&#xE693;',
		'Xrv'		=> '&#xE65F;',
		'Xsagittarius'		=> '&#xE64E;',
		'Xschool'		=> '&#xE73E;',
		'Xscissors'		=> '&#xE694;',
		'Xscorpio'		=> '&#xE64D;',
		'Xsearch'		=> '&#xE6DC;',
		'Xsecret'		=> '&#xE734;',
		'Xsetting'		=> '&#xE718;',
		'Xsharp'		=> '&#xE6E0;',
		'Xship'		=> '&#xE661;',
		'Xshoe'		=> '&#xE674;',
		'Xsignal'		=> '&#xE66D;',
		'Xski'		=> '&#xE657;',
		'Xsmile'		=> '&#xE6F0;',
		'Xsmoking'		=> '&#xE67F;',
		'Xsnow'		=> '&#xE641;',
		'Xspa'		=> '&#xE6F7;',
		'Xspade'		=> '&#xE68E;',
		'Xstar'		=> '™',
		'Xsunny'		=> '&#xE63E;',
		'Xtaurus'		=> '&#xE647;',
		'Xtel'		=> '&#xE687;',
		'Xtelto'		=> '&#xE6CE;',
		'Xtheater'		=> '&#xE677;',
		'Xthunder'		=> '&#xE642;',
		'Xticket'		=> '&#xE67E;',
		'Xtoilet'		=> '&#xE66E;',
		'Xtrademark'		=> '&#xE732;',
		'Xtrain'		=> '&#xE660;',
		'Xtravel'		=> '&#xE682;',
		'Xtree'		=> '&#xE6A4;',
		'Xtv'		=> '&#xE68A;',
		'Xtyphoon'		=> '&#xE643;',
		'Xvirgo'		=> '&#xE64B;',
		'Xwatch'		=> '&#xE71F;',
		'Xwave'		=> '&#xE73F;',
		'Xzzz'		=> '&#xE701;',
	),
	'au' => array(
	'Xaquarius'		=> '<img localsrc="202">',
	'Xarea'		=> '<img localsrc="113">',
	'Xaries'		=> '<img localsrc="192">',
	'Xatm'		=> '<img localsrc="205">',
	'Xbank'		=> '<img localsrc="212">',
	'Xbar'		=> '<img localsrc="52">',
	'Xbarber'		=> '<img localsrc="104">',
	'Xbeer'		=> '<img localsrc="65">',
	'Xbird'		=> '<img localsrc="78">',
	'Xbomb'		=> '<img localsrc="268">',
	'Xbook'		=> '<img localsrc="122">',
	'Xbuilding'		=> '<img localsrc="156">',
	'Xbulb'		=> '<img localsrc="77">',
	'Xcaf?'		=> '<img localsrc="93">',
	'Xcake'		=> '<img localsrc="313">',
	'Xcamera'		=> '<img localsrc="94">',
	'Xcamp'		=> '<img localsrc="311">',
	'Xcancer'		=> '<img localsrc="195">',
	'Xcapricorn'		=> '<img localsrc="201">',
	'Xcar'		=> '<img localsrc="125">',
	'Xcat'		=> '<img localsrc="251">',
	'Xcd'		=> '<img localsrc="300">',
	'Xcharge'		=> '<img localsrc="109">',
	'Xcheckerflag'		=> '<img localsrc="222">',
	'Xclock'		=> '<img localsrc="46">',
	'Xcloud'		=> '<img localsrc="107">',
	'Xclover'		=> '<img localsrc="53">',
	'Xclub'		=> '<img localsrc="316">',
	'Xcopyright'		=> '<img localsrc="81">',
	'Xcrown'		=> '<img localsrc="198">',
	'Xcvs'		=> '<img localsrc="206">',
	'Xdiacritic'		=> '<img localsrc="291">',
	'Xdiamond'		=> '<img localsrc="315">',
	'Xdocument'		=> '<img localsrc="142">',
	'Xdog'		=> '<img localsrc="74">',
	'Xear'		=> '<img localsrc="318">',
	'Xempty'		=> '<img localsrc="">',
	'Xfastfood'		=> '<img localsrc="245">',
	'Xfaxto'		=> '<img localsrc="166">',
	'Xfish'		=> '<img localsrc="203">',
	'Xflag'		=> '<img localsrc="306">',
	'Xfootball'		=> '<img localsrc="219">',
	'Xforbidden'		=> '<img localsrc="31">',
	'Xfree'		=> '<img localsrc="299">',
	'Xfull'		=> '<img localsrc="">',
	'Xgame'		=> '<img localsrc="232">',
	'Xgas'		=> '<img localsrc="213">',
	'Xgemini'		=> '<img localsrc="194">',
	'Xglasses'		=> '<img localsrc="116">',
	'Xgolf'		=> '<img localsrc="306">',
	'Xgood'		=> '<img localsrc="287">',
	'Xhandicapped'		=> '<img localsrc="178">',
	'Xheadset'		=> '<img localsrc="294">',
	'Xheart'		=> '<img localsrc="51">',
	'Xhorse'		=> '<img localsrc="248">',
	'Xhospital'		=> '<img localsrc="304">',
	'Xhotel'		=> '<img localsrc="112">',
	'Xhouse'		=> '<img localsrc="112">',
	'Xid'		=> '<img localsrc="">',
	'Xkaraoke'		=> '<img localsrc="289">',
	'Xkey'		=> '<img localsrc="120">',
	'Xleo'		=> '<img localsrc="196">',
	'Xlibra'		=> '<img localsrc="198">',
	'Xlip'		=> '<img localsrc="273">',
	'Xmail'		=> '<img localsrc="108">',
	'Xmailto'		=> '<img localsrc="151">',
	'Xmetro'		=> '<img localsrc="217">',
	'Xmobile'		=> '<img localsrc="161">',
	'Xmoney'		=> '<img localsrc="233">',
	'Xnew'		=> '<img localsrc="76">',
	'Xnosmoking'		=> '<img localsrc="177">',
	'Xnum0'		=> '<img localsrc="325">',
	'Xnum1'		=> '<img localsrc="180">',
	'Xnum2'		=> '<img localsrc="181">',
	'Xnum3'		=> '<img localsrc="182">',
	'Xnum4'		=> '<img localsrc="183">',
	'Xnum5'		=> '<img localsrc="184">',
	'Xnum6'		=> '<img localsrc="185">',
	'Xnum7'		=> '<img localsrc="186">',
	'Xnum8'		=> '<img localsrc="187">',
	'Xnum9'		=> '<img localsrc="188">',
	'Xok'		=> '<img localsrc="326">',
	'Xpaper'		=> '<img localsrc="320">',
	'Xparking'		=> '<img localsrc="208">',
	'Xpc'		=> '<img localsrc="288">',
	'Xpen'		=> '<img localsrc="149">',
	'Xpencil'		=> '<img localsrc="149">',
	'Xpenguin'		=> '<img localsrc="252">',
	'Xpeople'		=> '<img localsrc="80">',
	'Xpisces'		=> '<img localsrc="203">',
	'Xplain'		=> '<img localsrc="168">',
	'Xpost'		=> '<img localsrc="151">',
	'Xpresent'		=> '<img localsrc="165">',
	'Xrainy'		=> '<img localsrc="95">',
	'Xregarded'		=> '<img localsrc="82">',
	'Xrestaurant'		=> '<img localsrc="146">',
	'Xreturn'		=> '<img localsrc="118">',
	'Xribbon'		=> '<img localsrc="312">',
	'Xring'		=> '<img localsrc="72">',
	'Xrock'		=> '<img localsrc="281">',
	'Xrv'		=> '<img localsrc="148">',
	'Xsagittarius'		=> '<img localsrc="200">',
	'Xschool'		=> '<img localsrc="149">',
	'Xscissors'		=> '<img localsrc="319">',
	'Xscorpio'		=> '<img localsrc="199">',
	'Xsearch'		=> '<img localsrc="119">',
	'Xsecret'		=> '<img localsrc="279">',
	'Xsetting'		=> '<img localsrc="152">',
	'Xsharp'		=> '<img localsrc="">',
	'Xship'		=> '<img localsrc="169">',
	'Xshoe'		=> '<img localsrc="124">',
	'Xsignal'		=> '<img localsrc="99">',
	'Xski'		=> '<img localsrc="221">',
	'Xsmile'		=> '<img localsrc="68">',
	'Xsmoking'		=> '<img localsrc="176">',
	'Xsnow'		=> '<img localsrc="191">',
	'Xspa'		=> '<img localsrc="224">',
	'Xspade'		=> '<img localsrc="314">',
	'Xstar'		=> '<img localsrc="69">',
	'Xsunny'		=> '<img localsrc="44">',
	'Xtaurus'		=> '<img localsrc="193">',
	'Xtel'		=> '<img localsrc="85">',
	'Xtelto'		=> '<img localsrc="161">',
	'Xtheater'		=> '<img localsrc="110">',
	'Xthunder'		=> '<img localsrc="16">',
	'Xticket'		=> '<img localsrc="106">',
	'Xtoilet'		=> '<img localsrc="207">',
	'Xtrademark'		=> '<img localsrc="54">',
	'Xtrain'		=> '<img localsrc="216">',
	'Xtravel'		=> '<img localsrc="83">',
	'Xtree'		=> '<img localsrc="234">',
	'Xtv'		=> '<img localsrc="288">',
	'Xtyphoon'		=> '<img localsrc="190">',
	'Xvirgo'		=> '<img localsrc="197">',
	'Xwatch'		=> '<img localsrc="25">',
	'Xwave'		=> '<img localsrc="95">',
	'Xzzz'		=> '<img localsrc="261">',
	),
	'voda' => array(
	'Xaquarius'		=> '$Fi',
	'Xarea'		=> '$F$',
	'Xaries'		=> '$F_',
	'Xatm'		=> '$Et',
	'Xbank'		=> '$Em',
	'Xbar'		=> '$Gd',
	'Xbarber'		=> '$O3',
	'Xbeer'		=> '$Gg',
	'Xbird'		=> '$QC',
	'Xbomb'		=> '$O1',
	'Xbook'		=> '$Eh',
	'Xbuilding'		=> '$GX',
	'Xbulb'		=> '$E/',
	'Xcaf?'		=> '$Ge',
	'Xcake'		=> '$Ok',
	'Xcamera'		=> '$G(',
	'Xcamp'		=> '$EB',
	'Xcancer'		=> '$Fb',
	'Xcapricorn'		=> '$Fh',
	'Xcar'		=> '$Ez',
	'Xcat'		=> '$Go',
	'Xcd'		=> '$EF',
	'Xcharge'		=> '$F5',
	'Xcheckerflag'		=> '$ER',
	'Xclock'		=> '$GL',
	'Xcloud'		=> '$Gi',
	'Xclover'		=> '$E0',
	'Xclub'		=> '$F/',
	'Xcopyright'		=> '$Fn',
	'Xcrown'		=> '$E.',
	'Xcvs'		=> '$Ev',
	'Xdiacritic'		=> '$G^',
	'Xdiamond'		=> '$F-',
	'Xdocument'		=> '$O!',
	'Xdog'		=> '$Gr',
	'Xear'		=> '$P;',
	'Xempty'		=> '$FK',
	'Xfastfood'		=> '$E@',
	'Xfaxto'		=> '$G+',
	'Xfish'		=> '$G9',
	'Xflag'		=> '$Ek',
	'Xfootball'		=> '$G8',
	'Xforbidden'		=> '$OS',
	'Xfree'		=> '$F6',
	'Xfull'		=> '$FJ',
	'Xgame'		=> '$EK',
	'Xgas'		=> '$GZ',
	'Xgemini'		=> '$Fa',
	'Xglasses'		=> '$F1',
	'Xgolf'		=> '$G4',
	'Xgood'		=> '$G.',
	'Xhandicapped'		=> '$F*',
	'Xheadset'		=> '$O*',
	'Xheart'		=> '$F,',
	'Xhorse'		=> '$G:',
	'Xhospital'		=> '$Eu',
	'Xhotel'		=> '$Ex',
	'Xhouse'		=> '$GV',
	'Xid'		=> '$',
	'Xkaraoke'		=> '$G\',
	'Xkey'		=> '$G_',
	'Xleo'		=> '$Fc',
	'Xlibra'		=> '$Fe',
	'Xlip'		=> '$G#',
	'Xmail'		=> '$E#',
	'Xmailto'		=> '$E#',
	'Xmetro'		=> '$PT',
	'Xmobile'		=> '$G*',
	'Xmoney'		=> '$EO',
	'Xnew'		=> '$F2',
	'Xnosmoking'		=> '$F(',
	'Xnum0'		=> '$FE',
	'Xnum1'		=> '$F<',
	'Xnum2'		=> '$F=',
	'Xnum3'		=> '$F>',
	'Xnum4'		=> '$F?',
	'Xnum5'		=> '$F@',
	'Xnum6'		=> '$FA',
	'Xnum7'		=> '$FB',
	'Xnum8'		=> '$FC',
	'Xnum9'		=> '$FD',
	'Xok'		=> '$Fm',
	'Xpaper'		=> '$G2',
	'Xparking'		=> '$Eo',
	'Xpc'		=> '$G,',
	'Xpen'		=> '$O!',
	'Xpencil'		=> '$O!',
	'Xpenguin'		=> '$Gu',
	'Xpeople'		=> '$Fs',
	'Xpisces'		=> '$Fj',
	'Xplain'		=> '$G=',
	'Xpost'		=> '$Es',
	'Xpresent'		=> '$E2',
	'Xrainy'		=> '$Gk',
	'Xregarded'		=> '$Fo',
	'Xrestaurant'		=> '$Gc',
	'Xreturn'		=> '$F[',
	'Xribbon'		=> '$O4',
	'Xring'		=> '$GT',
	'Xrock'		=> '$G0',
	'Xrv'		=> '$$;',
	'Xsagittarius'		=> '$Fg',
	'Xschool'		=> '$Ew',
	'Xscissors'		=> '$G1',
	'Xscorpio'		=> '$Ff',
	'Xsearch'		=> '$E4',
	'Xsecret'		=> '$O5',
	'Xsetting'		=> '$E6',
	'Xsharp'		=> '$F0',
	'Xship'		=> '$F"',
	'Xshoe'		=> '$E^',
	'Xsignal'		=> '$En',
	'Xski'		=> '$G3',
	'Xsmile'		=> '$P5',
	'Xsmoking'		=> '$O.',
	'Xsnow'		=> '$Gh',
	'Xspa'		=> '$EC',
	'Xspade'		=> '$F.',
	'Xstar'		=> '$OO',
	'Xsunny'		=> '$Gj',
	'Xtaurus'		=> '$F`',
	'Xtel'		=> '$G)',
	'Xtelto'		=> '$E$',
	'Xtheater'		=> '$G]',
	'Xthunder'		=> '$E]',
	'Xticket'		=> '$EE',
	'Xtoilet'		=> '$Eq',
	'Xtrademark'		=> '$QW',
	'Xtrain'		=> '$Ey',
	'Xtravel'		=> '$E>',
	'Xtree'		=> '$GS',
	'Xtv'		=> '$EJ',
	'Xtyphoon'		=> '$Pc',
	'Xvirgo'		=> '$Fd',
	'Xwatch'		=> '$GF',
	'Xwave'		=> '$P^',
	'Xzzz'		=> '$E\',
	)
);
	function get_number_icon($k) {
	global $mobile_icons;
		$ua = null;

		if ( preg_match('/DoCoMo\//', $_SERVER['HTTP_USER_AGENT'], $m) ) {
			return $mobile_icons['docomo']["Xnum$k"];
		} elseif ( preg_match('/WILLCOM/', $_SERVER['HTTP_USER_AGENT'], $m) ) {
			return $mobile_icons['docomo']["Xnum$k"];
		} elseif ( preg_match('/KDDI-/', $_SERVER['HTTP_USER_AGENT'], $m) ) {
			$key = "Xnum$k";
			return $mobile_icons['au'][$key];
		} elseif ( preg_match('/^(MOT-|Vodafone|J-PHONE|SoftBank)/', $_SERVER['HTTP_USER_AGENT'], $m) ) {
			return $mobile_icons['voda']["Xnum$k"];
		} else {
			return '[' . ((string)$k) . ']';
		}
	}

?>
